import {
  CollectionItem,
  FounderPick,
  WhyUsItem,
  FounderContent,
  ExperienceContent,
  TestimonialItem,
  JournalPost,
  SiteSettings,
  HeroContent,
  MediaAsset,
} from './database.types';

export const defaultSettings: SiteSettings = {
  id: 'current',
  brand_name: 'GOLD N GLOW',
  tagline: "Hyderabad's Premier Artificial Bangle Boutique",
  positioning: "Hyderabad's Premier Designer Bangle Destination Since 2002",
  phone: '+91 98490 12345',
  whatsapp: '919849012345',
  email: 'concierge@goldnglow.in',
  address_line1: 'Near Pillar No. 65, Main Road, Tolichowki',
  address_line2: 'Hyderabad, Telangana 500008, India',
  store_timings: '11:00 AM – 9:30 PM',
  store_days: 'Monday through Sunday (Open All 7 Days)',
  google_maps_url: 'https://maps.google.com/?q=Tolichowki+Hyderabad',
  instagram_url: 'https://instagram.com',
  facebook_url: 'https://facebook.com',
  youtube_url: 'https://youtube.com',
};

export const defaultHeroContent: HeroContent = {
  id: 'current',
  badge_text: "INDIA'S FINEST CURATED BANGLES",
  heading_line1: 'Timeless Elegance.',
  heading_line2: 'Crafted to Perfection.',
  description: "For over two decades, Gold N Glow has been Hyderabad's destination for the world's most exquisite bangles.",
  primary_btn_text: 'EXPLORE COLLECTIONS',
  primary_btn_link: '#collections',
  secondary_btn_text: 'OUR STORY',
  secondary_btn_link: '#story',
  image_url: '/assets/hero/hero-bangles-luxury.jpg',
  video_url: 'https://res.cloudinary.com/akmdvmmw/video/upload/v1787937881/clean_13b7fcc9-fa81-4b3d-996b-d97360f4a902_tfdp9g.mp4',
  active: true,
  display_order: 1,
};

export const defaultFounderContent: FounderContent = {
  id: 'current',
  section_number: '03',
  section_tag: 'OUR JOURNEY SINCE 2002',
  heading_part1: 'A Legacy Built on',
  heading_accent: 'Trust,',
  heading_part2: 'Passion & Perfection.',
  story_p1:
    "What started in 2002 as a small dream has today become Hyderabad's most trusted name in bangles. Our promise remains the same — exceptional quality, honest value, and a shopping experience you'll always cherish.",
  story_p2:
    'Over two decades, we have become the city’s favorite destination for handcrafted bridal churas, royal Nizam-inspired imitation kadas, and vibrant festive sets for every generation.',
  founder_name: 'Syed Owais Ahmed',
  founder_role: 'FOUNDER, GOLD N GLOW',
  founder_image_url: '/assets/founder/syed-owais-ahmed.png',
  signature_image_url: '',
  founder_quote:
    '“A designer bangle is the heartbeat of festive tradition and personal elegance. Every imitation piece in our boutique is chosen with exquisite care.”',
  button_text: 'Read Full Heritage Story',
  button_link: '#about',
};

export const defaultCollections: CollectionItem[] = [
  // ── 1. HANDCRAFTED LAC BANGLES (Heritage Laakh & Jaipuri Craftsmanship) ──
  {
    id: 'lac-1',
    title: 'Tolichowki Heritage Mirror Lac Bangles',
    category: 'lac',
    material: 'Lac',
    subtitle: '100% Raw Lac resin with genuine mirror work',
    description: 'Authentic Hyderabadi handcrafted lac bangles studded with colored stones, sparkling mini mirrors, and brass reinforcement.',
    image_url: '/assets/collections/hyderabadi-lac.jpg',
    badge_label: 'HANDCRAFTED LAC',
    display_order: 1,
    featured: true,
    active: true,
  },
  {
    id: 'lac-2',
    title: 'Royal Nizami Kundan Lac Kadas',
    category: 'lac',
    material: 'Lac',
    subtitle: 'Pure Lac core with uncut Polki stone insets',
    description: 'Broad handcrafted openable Lac kadas embedded with uncut polki Kundan stones, emerald cabochons, and micro-bead accents.',
    image_url: '/assets/collections/kundan-bridal-kada.jpg',
    badge_label: 'POLKI LAC',
    display_order: 2,
    featured: true,
    active: true,
  },
  {
    id: 'lac-3',
    title: 'Jaipuri Meenakari Floral Lac Stack',
    category: 'lac',
    material: 'Lac',
    subtitle: 'Hand-painted pastel enamel on genuine Lac',
    description: 'Delicate floral Meenakari work fused onto durable molded Lac bangles with sparkling crystal borders.',
    image_url: '/assets/collections/meenakari-pastel.jpg',
    badge_label: 'MEENAKARI LAC',
    display_order: 3,
    featured: true,
    active: true,
  },
  {
    id: 'lac-4',
    title: 'Navratan Gemstone Studded Lac Set',
    category: 'lac',
    material: 'Lac',
    subtitle: 'Nine-gemstone celebratory Lac stack',
    description: 'Traditional heavy festive Lac bangles hand-set with vibrant nine-color astrological stones and golden zari lining.',
    image_url: '/assets/collections/navratan-gemstone.jpg',
    badge_label: 'NAVRATAN LAC',
    display_order: 4,
    featured: true,
    active: true,
  },
  {
    id: 'lac-5',
    title: 'Antique Filigree Brass-Lined Lac Kadas',
    category: 'lac',
    material: 'Lac',
    subtitle: 'Comfort-fit lac foundation with brass lattice',
    description: 'Hinged screw-openable kadas featuring a warm Lac resin interior adorned with intricate gold-finish filigree lattice.',
    image_url: '/assets/collections/antique-filigree.jpg',
    badge_label: 'FILIGREE LAC',
    display_order: 5,
    featured: false,
    active: true,
  },

  // ── 2. ARTISAN GLASS BANGLES (Velvet, Foiled, & Shimmer Glass) ──
  {
    id: 'glass-1',
    title: 'Velvet Matte Royal Glass Bangle Stack',
    category: 'glass',
    material: 'Glass',
    subtitle: 'Plush velvet finish on annealed artisan glass',
    description: 'Silky smooth velvet textured glass bangles in deep bridal maroon and emerald, bordered with fine micro-crystal spacers.',
    image_url: '/assets/collections/velvet-silk-thread.jpg',
    badge_label: 'VELVET GLASS',
    display_order: 6,
    featured: true,
    active: true,
  },
  {
    id: 'glass-2',
    title: 'Micro-Pavé American Diamond Glass Bangles',
    category: 'glass',
    material: 'Glass',
    subtitle: 'High-refraction CZ embedded on fine glass rims',
    description: 'Double-row brilliant cut cubic zirconia encased on durable gold-rimmed glass bangles for effortless daily sparkle.',
    image_url: '/assets/collections/cz-diamond-bangles.jpg',
    badge_label: 'DIAMOND GLASS',
    display_order: 7,
    featured: true,
    active: true,
  },
  {
    id: 'glass-3',
    title: 'Ruby & Emerald Cabochon Glass Bangles',
    category: 'glass',
    material: 'Glass',
    subtitle: 'Hand-carved temple glass with antique gold rims',
    description: 'Rich temple-carved motif glass bangles studded with ruby-red and emerald cabochons for festive celebrations.',
    image_url: '/assets/collections/ruby-emerald-temple.jpg',
    badge_label: 'TEMPLE GLASS',
    display_order: 8,
    featured: true,
    active: true,
  },
  {
    id: 'glass-4',
    title: 'Hyderabadi Basra Pearl Glass Bangle Suite',
    category: 'glass',
    material: 'Glass',
    subtitle: 'Multi-strand faux pearl rims on crystal glass',
    description: 'Authentic pearl-bordered glass bangles adorned with floral kundan centers for timeless royal Deccani elegance.',
    image_url: '/assets/collections/pearl-bangles-set.jpg',
    badge_label: 'PEARL GLASS',
    display_order: 9,
    featured: false,
    active: true,
  },
  {
    id: 'glass-5',
    title: 'Pink Tourmaline Shimmer Glass Stack',
    category: 'glass',
    material: 'Glass',
    subtitle: 'Rose-gold tone foiled crystal glass',
    description: 'Radiant oval pink tourmaline accents paired with brilliant multi-faceted shimmer glass bangles.',
    image_url: '/assets/collections/pink-tourmaline-cz.jpg',
    badge_label: 'ROSE GLASS',
    display_order: 10,
    featured: false,
    active: true,
  },
  {
    id: 'glass-6',
    title: 'Cobalt Sapphire Pavé Glass Bangles',
    category: 'glass',
    material: 'Glass',
    subtitle: 'Intense royal blue crystal glass cluster design',
    description: 'Dazzling sapphire blue glass bangles bordered with pave micro-crystals for glamorous evening galas.',
    image_url: '/assets/collections/sapphire-cz-bangles.jpg',
    badge_label: 'SAPPHIRE GLASS',
    display_order: 11,
    featured: false,
    active: true,
  },

  // ── 3. BRIDAL HERITAGE SETS (Categorized with Material Designation) ──
  {
    id: 'bridal-1',
    title: 'Royal Nizami Handcrafted Lac Bridal Kada Suite',
    category: 'bridal',
    material: 'Lac',
    subtitle: 'Heritage Bridal Trousseau • Pure Lac & Polki',
    description: 'Broad openable bridal Lac kadas encrusted with green onyx drops, uncut polki Kundan stones, and antique gold finish.',
    image_url: '/assets/collections/kundan-bridal-kada.jpg',
    badge_label: 'BRIDAL • LAC',
    display_order: 12,
    featured: true,
    active: true,
  },
  {
    id: 'bridal-2',
    title: 'Begum Jaan Velvet Glass Bridal Chooda',
    category: 'bridal',
    material: 'Glass',
    subtitle: 'Matrimonial Masterpiece • Velvet Glass Stack',
    description: 'Magnificent bridal stack combining maroon velvet glass bangles with heavy floral side kadas and seed pearl latkans.',
    image_url: '/assets/collections/velvet-silk-thread.jpg',
    badge_label: 'BRIDAL • GLASS',
    display_order: 13,
    featured: true,
    active: true,
  },
  {
    id: 'bridal-3',
    title: 'Maharani Grand Lac & Glass Bridal Ensemble',
    category: 'bridal',
    material: 'Lac & Glass',
    subtitle: 'Hybrid Bridal Suite • Handcrafted Lac + Glass Stack',
    description: 'The definitive Deccani wedding suite: centerpiece handcrafted Lac kadas flanked by 24 rich festive glass bangles.',
    image_url: '/assets/collections/bridal-heritage.jpg',
    badge_label: 'BRIDAL • LAC & GLASS',
    display_order: 14,
    featured: true,
    active: true,
  },
  {
    id: 'bridal-4',
    title: 'Shahi Jadau Pearl Lac Bridal Chooda',
    category: 'bridal',
    material: 'Lac',
    subtitle: 'Heritage Wedding Chooda • Hand-Set Pearl Lac',
    description: 'Multi-piece royal bridal Lac suite featuring floral Kundan centerpieces and cascading Basra pearl latkans.',
    image_url: '/assets/collections/jadau-openable.jpg',
    badge_label: 'BRIDAL • LAC',
    display_order: 15,
    featured: true,
    active: true,
  },
  {
    id: 'bridal-5',
    title: 'Rajputana Royal Navratan Lac Bridal Suite',
    category: 'bridal',
    material: 'Lac',
    subtitle: 'Nine-gemstone wedding kada pair on pure Lac',
    description: 'Heavy openable kadas encrusted with nine vibrant astrological gemstones on handcrafted durable Lac.',
    image_url: '/assets/collections/navratan-gemstone.jpg',
    badge_label: 'BRIDAL • LAC',
    display_order: 16,
    featured: false,
    active: true,
  },
  {
    id: 'bridal-6',
    title: 'Noor Mahal Velvet Glass & Kundan Bridal Stack',
    category: 'bridal',
    material: 'Glass',
    subtitle: 'Plush bridal maroon velvet glass with golden borders',
    description: 'Royal velvet glass bangles with shimmering micro-crystal borders and heavy gold-finish side kadas.',
    image_url: '/assets/collections/velvet-silk-thread.jpg',
    badge_label: 'BRIDAL • GLASS',
    display_order: 17,
    featured: false,
    active: true,
  },
  {
    id: 'bridal-7',
    title: 'Gulzar Pink Tourmaline Crystal Glass Bridal Stack',
    category: 'bridal',
    material: 'Glass',
    subtitle: 'Rose-gold foiled glass with American diamond accents',
    description: 'Modern bridal elegance designed for pastel pink, ivory, and blush designer wedding lehengas.',
    image_url: '/assets/collections/pink-tourmaline-cz.jpg',
    badge_label: 'BRIDAL • GLASS',
    display_order: 18,
    featured: false,
    active: true,
  },
  {
    id: 'bridal-8',
    title: 'Tolichowki Heritage Lac Bridal Box (12 Pairs)',
    category: 'bridal',
    material: 'Lac',
    subtitle: 'Complete handcrafted wedding trousseau box',
    description: 'Heritage red and turquoise lac bangles with genuine mirror work crafted by Tolichowki master artisans.',
    image_url: '/assets/collections/hyderabadi-lac.jpg',
    badge_label: 'BRIDAL • LAC',
    display_order: 19,
    featured: false,
    active: true,
  },
];

export const defaultFounderPicks: FounderPick[] = [
  {
    id: 'fp-1',
    pick_number: '01',
    title: 'Royal Kundan & Polki Lac Master Kada',
    tagline: 'Handcrafted raw Lac with polki & emerald stones',
    description: '100% natural Lac resin core with uncut polki Kundan stones and vivid emerald bead embellishments.',
    image_url: '/assets/collections/kundan-bridal-kada.jpg',
    display_order: 1,
    active: true,
  },
  {
    id: 'fp-2',
    pick_number: '02',
    title: 'Micro-Pavé Cubic Zirconia Glass Stack',
    tagline: 'Annealed artisan glass with American diamond rims',
    description: 'Double-tier faceted CZ bangles set on fine annealed glass with smooth inner contouring.',
    image_url: '/assets/collections/cz-diamond-bangles.jpg',
    display_order: 2,
    active: true,
  },
  {
    id: 'fp-3',
    pick_number: '03',
    title: 'Tolichowki Heritage Mirror Lac Bangles',
    tagline: 'Centuries-old Laakh craftsmanship with mirror insets',
    description: 'Iconic Hyderabadi handcrafted lac bangles studded with colored stones and hand-cut mirrors.',
    image_url: '/assets/collections/hyderabadi-lac.jpg',
    display_order: 3,
    active: true,
  },
  {
    id: 'fp-4',
    pick_number: '04',
    title: 'Royal Velvet Matte Glass Bangle Stack',
    tagline: 'Plush bridal maroon velvet on fine glass',
    description: 'Sensory velvet texture with sparkling micro-crystal borders and gold-finish side kadas.',
    image_url: '/assets/collections/velvet-silk-thread.jpg',
    display_order: 4,
    active: true,
  },
];

export const defaultWhyUs: WhyUsItem[] = [
  {
    id: 'why-1',
    title: '500+ HANDPICKED DESIGNS',
    subtitle: 'Curated by Syed Owais Ahmed',
    category: 'pill',
    icon_name: 'Crown',
    display_order: 1,
    active: true,
  },
  {
    id: 'why-2',
    title: 'CUSTOM WRIST SIZING',
    subtitle: 'Sizes 2.2 to 2.10 & Bespoke Sets',
    category: 'pill',
    icon_name: 'Sparkles',
    display_order: 2,
    active: true,
  },
  {
    id: 'why-3',
    title: '22+ YEARS IN TOLICHOWKI',
    subtitle: 'Beloved Hyderabad Bangle Landmark',
    category: 'pill',
    icon_name: 'Award',
    display_order: 3,
    active: true,
  },
  {
    id: 'why-4',
    title: 'WORLDWIDE SECURE DELIVERY',
    subtitle: 'Express Tracked Shipping for NRIs',
    category: 'pill',
    icon_name: 'ShieldCheck',
    display_order: 4,
    active: true,
  },
  {
    id: 'why-5',
    title: 'PREMIUM ARTISAN KARIGARI',
    subtitle: 'Handcrafted settings & long-lasting finish',
    category: 'promise',
    icon_name: 'Gem',
    display_order: 5,
    active: true,
  },
  {
    id: 'why-6',
    title: 'TRANSPARENT DIRECT PRICING',
    subtitle: 'Fair boutique pricing on artificial bangles',
    category: 'promise',
    icon_name: 'ShieldCheck',
    display_order: 6,
    active: true,
  },
  {
    id: 'why-7',
    title: 'PERSONAL STYLING SESSIONS',
    subtitle: 'In-store or live WhatsApp video consultations',
    category: 'promise',
    icon_name: 'Users',
    display_order: 7,
    active: true,
  },
  {
    id: 'why-8',
    title: 'SAFE & SECURE PACKAGING',
    subtitle: 'Signature velvet gift box packaging',
    category: 'promise',
    icon_name: 'Lock',
    display_order: 8,
    active: true,
  },
];

export const defaultExperience: ExperienceContent = {
  id: 'current',
  section_number: '08',
  heading_line1: 'The In-Store Experience',
  heading_line2: 'Step inside Hyderabad’s favorite bangle showroom in Tolichowki.',
  description:
    'Experience over 500+ handcrafted artificial bangle designs in person. Feel the weight, examine the stone settings, and let our bridal stylists curate the exact stack for your wedding or celebration.',
  button_text: 'Book Showroom Visit',
  main_image_url: '/assets/store/store-interior-main.jpg',
  exterior_image_url: '/assets/store/store-exterior.jpg',
  showcase_image_url: '/assets/store/store-showcase.jpg',
  customers_image_url: '/assets/store/store-interior-main.jpg',
  video_url: '',
};

export const defaultTestimonials: TestimonialItem[] = [
  {
    id: 't-1',
    customer_name: 'Ayesha Fatima',
    customer_location: 'Banjara Hills, Hyderabad',
    rating: 5,
    testimonial:
      'Gold N Glow created the most breathtaking bridal kada set for my wedding. The fitting was flawless, and the craftsmanship looked like pure heirloom jewelry!',
    photo_url: '',
    display_order: 1,
    published: true,
  },
  {
    id: 't-2',
    customer_name: 'Dr. Sameera Khan',
    customer_location: 'Jubilee Hills, Hyderabad',
    rating: 5,
    testimonial:
      'I have been purchasing bangles from Syed Owais Ahmed Uncle for over 15 years. Their variety of velvet and stone bangles in Tolichowki is unmatched anywhere in Telangana.',
    photo_url: '',
    display_order: 2,
    published: true,
  },
  {
    id: 't-3',
    customer_name: 'Farzana Begum',
    customer_location: 'London, United Kingdom (NRI)',
    rating: 5,
    testimonial:
      'Ordered 6 bridal sets over WhatsApp video call for my daughter’s wedding in the UK. They arrived within 5 days in pristine velvet boxes. Exceptional service!',
    photo_url: '',
    display_order: 3,
    published: true,
  },
];

export const defaultJournal: JournalPost[] = [
  {
    id: 'post-1',
    title: 'The Nizam Legacy: How Royal Hyderabad Shaped Indian Bangle Design',
    slug: 'nizam-legacy-bangle-design',
    category: 'HERITAGE & CRAFT',
    excerpt: 'Explore the fascinating history of Nizami jewellery craftsmanship and how uncut polki and meenakari became the crown jewels of Hyderabad.',
    content: `Explore the fascinating history of Nizami jewellery craftsmanship and how uncut polki and meenakari became the crown jewels of Hyderabad.`,
    cover_image_url: '/assets/journal/journal-card-1.jpg',
    published_date: 'February 2025',
    author: 'Syed Owais Ahmed',
    published: true,
    display_order: 1,
  },
  {
    id: 'post-2',
    title: 'Bridal Bangle Stacking 101: The Rule of Proportions',
    slug: 'bridal-bangle-stacking-proportions',
    category: 'STYLING GUIDE',
    excerpt: 'A comprehensive visual guide to balancing kadas, thin chudiyan, and patlis for a grand bridal ensemble that feels regal yet weightless.',
    content: `A comprehensive visual guide to balancing kadas, thin chudiyan, and patlis for a grand bridal ensemble that feels regal yet weightless.`,
    cover_image_url: '/assets/journal/journal-card-2.jpg',
    published_date: 'January 2025',
    author: 'Gold N Glow Stylist Team',
    published: true,
    display_order: 2,
  },
  {
    id: 'post-3',
    title: 'How to Measure Your Wrist for the Perfect Bangle Fit',
    slug: 'measure-wrist-bangle-fit-guide',
    category: 'BUYER’S GUIDE',
    excerpt: 'Step-by-step instructions to find your exact Indian bangle size (from 2.2 to 2.10) with ease before ordering online or visiting our showroom.',
    content: `Step-by-step instructions to find your exact Indian bangle size (from 2.2 to 2.10) with ease before ordering online or visiting our showroom.`,
    cover_image_url: '/assets/journal/journal-card-3.jpg',
    published_date: 'January 2025',
    author: 'Gold N Glow Stylist Team',
    published: true,
    display_order: 3,
  },
  {
    id: 'post-4',
    title: 'Preserving the Luster: Care & Maintenance of Kundan & Polki',
    slug: 'care-maintenance-kundan-polki',
    category: 'CARE & MAINTENANCE',
    excerpt: 'Simple yet essential tips from our master craftsmen on keeping your precious bangles shining bright across generations.',
    content: `Simple yet essential tips from our master craftsmen on keeping your precious bangles shining bright across generations.`,
    cover_image_url: '/assets/journal/journal-card-4.jpg',
    published_date: 'January 2025',
    author: 'Syed Owais Ahmed',
    published: true,
    display_order: 4,
  },
];

export const defaultMediaAssets: MediaAsset[] = [
  {
    id: 'media-1',
    file_name: 'kundan-bridal-kada.jpg',
    file_path: '/assets/collections/kundan-bridal-kada.jpg',
    file_url: '/assets/collections/kundan-bridal-kada.jpg',
    category: 'collections',
    alt_text: 'Royal Nizami Kundan Bridal Kada',
    created_at: new Date().toISOString(),
  },
  {
    id: 'media-2',
    file_name: 'cz-diamond-bangles.jpg',
    file_path: '/assets/collections/cz-diamond-bangles.jpg',
    file_url: '/assets/collections/cz-diamond-bangles.jpg',
    category: 'collections',
    alt_text: 'Micro Pavé Cubic Zirconia Bangles',
    created_at: new Date().toISOString(),
  },
  {
    id: 'media-3',
    file_name: 'ruby-emerald-temple.jpg',
    file_path: '/assets/collections/ruby-emerald-temple.jpg',
    file_url: '/assets/collections/ruby-emerald-temple.jpg',
    category: 'collections',
    alt_text: 'Ruby and Emerald Temple Bangles',
    created_at: new Date().toISOString(),
  },
];

export const defaultSiteSettings = defaultSettings;
export const defaultStripCollections = defaultCollections.filter((c) => c.category === 'strip');
export const defaultSignatureCollections = defaultCollections.filter((c) => c.category === 'signature');
export const defaultWhyUsItems = defaultWhyUs;
export const defaultExperienceContent = defaultExperience;
export const defaultJournalPosts = defaultJournal;

